# Generated by Django 2.2 on 2019-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='stu_num',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构'), (3, '讲师')], default=1, verbose_name='收藏类型'),
        ),
    ]
