# Generated by Django 2.2 on 2019-07-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190714_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='stu_num',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(default=123, max_length=50, verbose_name='课程名'),
            preserve_default=False,
        ),
    ]
