# Generated by Django 2.2 on 2019-07-14 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('tag', models.CharField(default='全国知名', max_length=10, verbose_name='机构标签')),
                ('category', models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='pxjg', max_length=4, verbose_name='类别')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数)')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数)')),
                ('stu_num', models.IntegerField(default=0, verbose_name='学习人数)')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数)')),
                ('address', models.CharField(max_length=150, verbose_name='机构地址')),
                ('logo', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(default=18, verbose_name='年龄)')),
                ('work_year', models.IntegerField(default=0, verbose_name='工作年限)')),
                ('work_company', models.CharField(max_length=50, verbose_name='就职公司')),
                ('work_position', models.CharField(max_length=50, verbose_name='公司职位')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数)')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数)')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='头像')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
    ]
